/**
 * PDF Audit Section
 *
 * Generates a transparent decision history section.
 *
 * This section provides:
 * - User actions
 * - AI decisions
 * - Evaluation modules
 * - Scores
 * - Explanations
 */

import {
    safeNumber,
    formatDateTime,
    formatDecimal
} from "../shared/formatter.js";


export function renderAuditSection(report = {}) {

    const audit =
        report.audit ?? [];


    return `

<section class="section">


<div class="section-title">

Decision Audit Trail

</div>



<div class="card"

style="
margin-bottom:25px;
">

<div class="card-title">

Transparency Overview

</div>


<div
style="
line-height:2;
font-size:14px;
">

This section provides a complete history of
decision evaluation steps generated by the
Municipality AI Decision Support Platform.

</div>


</div>




<table>

<thead>

<tr>

<th>

#

</th>


<th>

Date

</th>


<th>

User

</th>


<th>

Action

</th>


<th>

Module

</th>


<th>

Score

</th>


<th>

Status

</th>


<th>

Details

</th>


</tr>

</thead>


<tbody>


${audit

.map(

(item,index)=>`


<tr>


<td>

${index + 1}

</td>


<td>

${formatDateTime(item.date)}

</td>


<td>

${escapeHtml(

item.user ?? "System"

)}

</td>


<td>

${escapeHtml(

item.action ?? "-"

)}

</td>


<td>

${escapeHtml(

item.module ?? "-"

)}

</td>


<td>

${formatDecimal(

safeNumber(item.score)

)}

</td>


<td>

${status(

safeNumber(item.score)

)}

</td>


<td

style="
text-align:right;
">

${escapeHtml(

item.details ?? "-"

)}

</td>


</tr>


`

)

.join("")}


</tbody>


</table>



<div

class="card"

style="
margin-top:30px;
">


<div class="card-title">

Governance Statement

</div>


<p

style="
line-height:2;
text-align:justify;
">

All decisions recorded in this report are
traceable through the audit trail.
The system preserves evaluation history to
support accountability, transparency and
future review processes.

</p>


</div>



</section>



<div class="page-break"></div>


`;

}



function status(score) {


    if (score >= 90) {

        return badge(

            "Excellent",

            "#16A34A"

        );

    }


    if (score >= 75) {

        return badge(

            "Approved",

            "#2563EB"

        );

    }


    if (score >= 60) {

        return badge(

            "Review",

            "#F59E0B"

        );

    }


    return badge(

        "Critical",

        "#DC2626"

    );


}



function badge(text,color) {


    return `


<span

class="badge"

style="
background:${color};
">

${text}

</span>


`;

}



function escapeHtml(value) {


    return String(value)

        .replace(

            /&/g,

            "&amp;"

        )

        .replace(

            /</g,

            "&lt;"

        )

        .replace(

            />/g,

            "&gt;"

        )

        .replace(

            /"/g,

            "&quot;"

        )

        .replace(

            /'/g,

            "&#039;"

        );

}